# Generated by Django 5.0.2 on 2024-02-16 20:37

import src.django_project.cast_member.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=src.django_project.cast_member.models.cast_member_choices, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'cast_members',
                'db_table': 'cast_member',
            },
        ),
    ]
