# Generated by Django 5.0.2 on 2024-02-13 13:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_app', '0001_create_category_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(related_name='genres', to='category_app.category')),
            ],
            options={
                'verbose_name_plural': 'genres',
                'db_table': 'genre',
            },
        ),
    ]
